### ISSUE TITLE
Where is the config directory btw?

### ISSUE THREAD

**Issue by ourway** [Silver-Tree/currency-trend-ex#1]

**Comment by Tyler-pierce** [comment]
It's an early project so it wasn't set up for consumption generally yet. I'll add an example config today though and you can run it if you like. Cheers

**Comment by Tyler-pierce** [comment]
example configs for all conf files added.  Like I said this is early days but the migrations and running locally should work so please let me know if there's an issue

**Comment by ourway** [comment]
Thank you.  great
